### ISSUE TITLE
File Permission Problem with this Role

### ISSUE THREAD

**Issue by boscho87** [webarchitect609/ansible-role-jet-brains-toolbox#6]
Hey thanks for your work here

Sorry i'am new to ansible. Maybe ist just me. But when i try to user the role get this output, when i use this in a playbook:

> fatal: [127.0.0.1]: FAILED! => {"changed": false, "dest": "/opt", "extract_results": {"cmd": ["/usr/bin/tar", "--extract", "-C", "/opt", "-z", "-f", "/tmp/jetbrains-toolbox-1.20.8804.tar.gz"], "err": "/usr/bin/tar: jetbrains-toolbox-1.20.8804: Cannot mkdir: Permission denied\n/usr/bin/tar: jetbrains-toolbox-1.20.8804: Cannot mkdir: Permission denied\n/usr/bin/tar: jetbrains-toolbox-1.20.8804/jetbrains-toolbox: Cannot open: No such file or directory\n/usr/bin/tar: Exiting with failure status due to previous errors\n", "out": "", "rc": 2}, "gid": 0, "group": "root", "handler": "TgzArchive", "mode": "0755", "msg": "failed to unpack /tmp/jetbrains-toolbox-1.20.8804.tar.gz to /opt", "owner": "root", "size": 4096, "src": "/tmp/jetbrains-toolbox-1.20.8804.tar.gz", "state": "directory", "uid": 0}

**Comment by boscho87** [comment]
@webarchitect609 

Hey, maybe i am missing something, or is there a change needed in the ansible scripts?

**Comment by webarchitect609** [comment]
@boscho87 , looks like you forgot to
```
become: true
```
This role should be executed with [root priviledges](https://docs.ansible.com/ansible/latest/user_guide/become.html) since it installs the application.
